VentaAutomoviles/Models/AutomovilesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VentaAutomoviles.Models
{
    public class AutomovilesViewModel
    {
        private VentaAutomovilesEntities db = new VentaAutomovilesEntities();

        public AutomovilesViewModel(Automovil automovil)
        {
            this.IdAutomovil = automovil.IdAutomovil;
            this.IdTipoAutomovil = automovil.IdTipoAutomovil;
            this.TipoAutomovil = automovil.TipoAutomovil;
            this.IdModelo = automovil.IdModelo;
            this.Modelo = automovil.Modelo;
            this.Precio = automovil.Precio;
            this.IdTipoCombustible = automovil.IdTipoCombustible;
            this.TipoCombustible = automovil.TipoCombustible;
            this.Marca = db.Marca.Find(automovil.Modelo.IdMarca);
            var paquete =
                    from F in db.Fotografia
                    from FXA in db.FotografiaPorAutomovil
                    where FXA.IdFotografia == F.IdFotografia
                    where FXA.IdAutomovil == automovil.IdAutomovil
                    select F.IdFotografia;
            this.Fotos = paquete.ToList();
        }

        [Key]
        public int IdAutomovil { get; set; }

        [Required]
        [Display(Name = "Tipo de automovil")]
        public int IdTipoAutomovil { get; set; }

        public int IdModelo { get; set; }

        public int IdTipoCombustible { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public decimal Precio { get; set; }

        public virtual Modelo Modelo { get; set; }

        public virtual TipoAutomovil TipoAutomovil { get; set; }

        public virtual TipoCombustible TipoCombustible { get; set; }
        public Marca Marca { get; set; }
        public List<int> Fotos { get; set; }
    }
}

VentaAutomoviles/Controllers/AutomovilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VentaAutomoviles.Models;

namespace VentaAutomoviles.Controllers
{
    public class AutomovilesController : Controller
    {
        private VentaAutomovilesEntities db = new VentaAutomovilesEntities();

        // GET: Automoviles
        public ActionResult Index()
        {
            var automovil = db.Automovil.Include(a => a.Modelo).Include(a => a.TipoAutomovil).Include(a => a.TipoCombustible);
            return View(automovil.ToList());
        }

        public ActionResult IndexCliente()
        {
            var automovil = db.Automovil.Include(a => a.Modelo).Include(a => a.TipoAutomovil).Include(a => a.TipoCombustible);
            return View(automovil.ToList());
        }

        // GET: Automoviles/Details/5
        public ActionResult DetailsFactura(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Automovil automovil = db.Automovil.Find(id);
            if (automovil == null)
            {
                return HttpNotFound();
            }

            var viewModel = new AutomovilesViewModel(automovil);
            return View(viewModel);
        }

        public ActionResult DetailsCliente(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Automovil automovil = db.Automovil.Find(id);
            if (automovil == null)
            {
                return HttpNotFound();
            }

            return View(automovil);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VentaAutomoviles/Views/Automoviles/DetailsCliente.cshtml
@model VentaAutomoviles.Models.Automovil

@{
    ViewBag.Title = "DetailsCliente";
}

<h2>Automovil</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAutomovil.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAutomovil.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Volver", "IndexCliente", "Automoviles", null, new { @class = "btn btn-outline-primary mr-1" })
</p>

VentaAutomoviles/Views/Automoviles/DetailsFactura.cshtml
@model VentaAutomoviles.Models.AutomovilesViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAutomovil.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAutomovil.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        @foreach (var foto in Model.Fotos)
        {
            <dd>
                <img src="@Url.Action("Show", "Image", new { id = foto } ) " class="square rounded" />
            </dd>
        }

        <dd>
            <div>
                @Html.ActionLink("Facturar", "Create", "Facturas",  new { id = Model.IdAutomovil }, new { @class = "btn btn-success mr-1" })
            </div>
        </dd>
    </dl>
</div>



<div>
    @Html.ActionLink("Volver", "Index", "Automoviles", null, new { @class = "btn btn-outline-primary mr-1" })
</div>

VentaAutomoviles/Views/Automoviles/Index.cshtml
@model IEnumerable<VentaAutomoviles.Models.Automovil>

@{
    ViewBag.Title = "Index";
}

<h2>Automoviles disponibles</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAutomovil.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoAutomovil.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoCombustible.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.ActionLink("Facturar", "DetailsFactura", new { id=item.IdAutomovil }, new { @class = "btn btn-outline-secondary btn-sm mr-1" })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Volver", "IndexFacturador", "Home", new { @class = "btn btn-outline-primary mr-1" })
</div>

VentaAutomoviles/Views/Automoviles/IndexCliente.cshtml
@model IEnumerable<VentaAutomoviles.Models.Automovil>

@{
    ViewBag.Title = "Index";
}

<h2>Automoviles disponibles</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAutomovil.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoAutomovil.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoCombustible.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.ActionLink("Detalles", "DetailsCliente", new { id=item.IdAutomovil }, new { @class = "btn btn-outline-secondary btn-sm mr-1" })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Volver", "IndexCliente", "Home", new { @class = "btn btn-outline-primary mr-1" })
</div>